### ISSUE TITLE
Link to bootstrap-material-datetime-picker

### ISSUE THREAD

**Issue by devleaks** [e-frank/yii2-bootstrap-material-datetime-picker#2]
Hello,
Would it be possible to adjust your code to link to bootstrap-material-datetime-picker
"require": {
        "bower-asset/bootstrap-material-datetime-picker":  "*"
    },
rather than include all assets in your package?
Thank you.
Best regards.
Pierre

**Comment by e-frank** [comment]
i tried to make two minor changes with a pull-request, but the owner did not accept.
those are:
1. get default language from config or momentjs, instead 'en'
2. add an option for "autoOpen". i wanted this to programmatically open datepicker by a button/Icon instead on "focus".

so here is an updated copy.
